# Usando banco em memoria H2 para testes isolados, o parâmetro DB_CLOSE_DELAY=-1 impede que o banco seja apagado quando a última conexão for fechada
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
# Serve para indicar ao Spring Boot qual driver Java (JDBC) deve ser carregado para fazer a comunicação com o banco H2
spring.datasource.driverClassName=org.h2.Driver
# Define o nome de usuario administrador
spring.datasource.username=sa
# Define a senha de usuario administrador
spring.datasource.password=

# Define como o Hibernate gerenciará o banco de dados, o create-drop faz com que o Hibernate leia todas as classes com @Entity e apagas as tabelas existentes recriando todas do zero
spring.jpa.hibernate.ddl-auto=create-drop
# Define qual linguagem de SQL específica deve ser usada
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect