# Porta padrão enviada pela plataforma de Hospedagem (AWS, Render, Docker, etc.)
server.port=${PORT:8080}

# Se conecta ao banco de dados (Injetando as variáveis de ambiente)
spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Para verificar e validae se a estrutura do banco de dados corresponde às classes do Java
spring.jpa.hibernate.ddl-auto=validate
# Mostra os comandos SQL gerados pelo hibernate no console após fazer alguma operação
spring.jpa.show-sql=false

# Definir o nível de severidade padrão de todas as mensagens de log da sua aplicação e de todas as bibliotecas externas que ela utiliza
logging.level.root=WARN
# Exibe apenas as mensagens informativas de rotina (como inicialização e eventos importantes) e ocultando mensagens de depuração
logging.level.com.seuusuario=INFO