# Nome da aplicação
spring.application.name=order-payment-management

# Seleciona o ambiente(precisa ser mudado conforme
spring.profiles.active=dev

# Define o formato de data e hora que será armazenado na API
spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ss'Z'
# Define o fuso horário global
spring.jackson.time-zone=UTC